//
// Created by capitalg on 9/21/17.
//

#ifndef COMPILER_CONSTANTS_H
#define COMPILER_CONSTANTS_H
enum class tag {
    ID=256,  KEYWORD, DELIMITER, NONE,
    CHAR, STRING, REAL, INTEGER, // for Type of constant
    CONSTANT, // CHAR, STRING, REAL, INTEGER is CONSTANT

    TYPE_CHAR, TYPE_REAL, TYPE_INTEGER, TYPE_BOOL, TYPE_STRING,  // for Type
    BASIC_TYPE, // TYPE CHAR, REAL, INTEGER is basic Type
    TYPE_ARRAY,
    TYPE_FUNC,

    INDEX_TYPE_LVALUE, INDEX_TYPE_NUM,

    OR, AND, REVERSE, EQ, NE, GT, LT, LE, GE,
    ADD, SUB, MULTIPLY, DEVIDE, MINUS,


    BOOL, JOIN, EQUALITY, REL, EXPR, TERM, UNARY, FACTOR,

    TRUE, FALSE,
    IF, ELSE, WHILE, FOR, SWITCH, BREAK, CONTINUE, RETURN


};


#endif //COMPILER_CONSTANTS_H
